apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/reservation-system-437104/payments/production
          name: production
          env:
            - name: PORT
              value: '3001'
            - name: NOTIFCATIONS_HOST
              value: 'notifications'
            - name: NOTIFCATIONS_PORT
              value: '3000'
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
          ports:
            - containerPort: 3001
